users:
  - olagoldstx

exclude_name_contains:
  - trumind
  - psychiatry

readme:
  start_marker: "<!-- BADGES:START -->"
  end_marker: "<!-- BADGES:END -->"
  style: "for-the-badge"
  theme:
    labelColor: "0f172a"

default_badges:
  - type: github_license
  - type: github_stars
  - type: last_commit
  - type: issues
  - type: prs
  - type: repo_size
  - type: languages
  - type: workflow_status

topic_badges:
  terraform:
    - type: custom
      label: Terraform
      message: Ready
      color: "5c4ee5"
      logo: terraform
  kubernetes:
    - type: custom
      label: Kubernetes
      message: Hardened
      color: "326ce5"
      logo: kubernetes
  security:
    - type: custom
      label: Security
      message: Zero–Trust
      color: "0ea5e9"
      logo: auth0
  ai:
    - type: custom
      label: AI
      message: Safe-by-Design
      color: "111827"
      logo: openai

workflow:
  file: ".github/workflows/ci.yml"

site_export:
  path: "site/badges.json"

branch:
  name_prefix: "chore/badges-"
  commit_message: "chore: add/update Shields.io badges"
  pr_title_prefix: "chore: badges for"
