name: badges
on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 1"

permissions:
  contents: write
  pull-requests: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"   # (pin a stable version)

      - run: pip install pyyaml requests

      - name: Run updater
        env:
          # IMPORTANT: use your PAT secret so the script can write to other repos
          GITHUB_TOKEN: ${{ secrets.BADGE_PAT }}
        run: python scripts/update_readmes.py

      - name: Upload site export
        uses: actions/upload-artifact@v4
        with:
          name: badges-json
          path: site/badges.json
